version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_queue
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    dns: 
      - 8.8.8.8
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: celery_worker
    command: celery -A tasks.celery_app worker --loglevel=info -P prefork -c 1
    volumes:
      - ./worker:/app
      - ./shared:/app/shared
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      api:
        condition: service_started

volumes:
  postgres_data:
